# Generated by Django 3.1.3 on 2021-01-23 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_auto_20210122_1637'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='path',
        ),
        migrations.AddField(
            model_name='image',
            name='image_url',
            field=models.URLField(default='https://placekitten.com/2000/3000'),
            preserve_default=False,
        ),
    ]
