# Generated by Django 3.1.3 on 2021-01-23 09:13

import django.core.validators
from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, unique=True)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_of_study', models.CharField(max_length=120)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(null=True)),
                ('institution', models.CharField(max_length=120)),
                ('short_description', models.CharField(max_length=150)),
                ('display', models.BooleanField()),
            ],
            options={
                'ordering': ['start_date'],
            },
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('percentage', models.IntegerField(default=60, validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(1)])),
                ('display', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Work',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_title', models.CharField(max_length=120)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(null=True)),
                ('company', models.CharField(max_length=120)),
                ('short_description', models.CharField(max_length=150)),
                ('display', models.BooleanField()),
            ],
            options={
                'ordering': ['start_date'],
            },
        ),
    ]
