# Generated by Django 3.1.3 on 2021-01-23 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing_page', '0002_auto_20210123_1021'),
    ]

    operations = [
        migrations.AlterField(
            model_name='education',
            name='display',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='skill',
            name='display',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='work',
            name='display',
            field=models.BooleanField(default=True),
        ),
    ]
