# Generated by Django 3.1.3 on 2021-01-23 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing_page', '0004_auto_20210123_1139'),
    ]

    operations = [
        migrations.AddField(
            model_name='webinfo',
            name='avatar_url',
            field=models.URLField(default='http://placekitten.com/g/200/300'),
            preserve_default=False,
        ),
    ]
