# Generated by Django 3.1.3 on 2021-01-23 10:53

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('landing_page', '0006_auto_20210123_1143'),
    ]

    operations = [
        migrations.AddField(
            model_name='webinfo',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
