# Generated by Django 3.1.3 on 2021-01-26 10:43

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('landing_page', '0007_webinfo_created_on'),
    ]

    operations = [
        migrations.AlterField(
            model_name='webinfo',
            name='hobbies_text',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='webinfo',
            name='welcome_message',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
