# Generated by Django 3.1.3 on 2021-01-26 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing_page', '0008_auto_20210126_1143'),
    ]

    operations = [
        migrations.AlterField(
            model_name='webinfo',
            name='welcome_message',
            field=models.CharField(max_length=255),
        ),
    ]
