# Generated by Django 3.1.3 on 2021-01-26 11:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('landing_page', '0009_auto_20210126_1146'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='WebInfo',
            new_name='SiteConfiguration',
        ),
        migrations.AlterModelOptions(
            name='education',
            options={'ordering': ['start_date'], 'verbose_name': 'Education'},
        ),
        migrations.AlterModelOptions(
            name='siteconfiguration',
            options={'verbose_name': 'Site Configuration'},
        ),
        migrations.AlterModelOptions(
            name='work',
            options={'ordering': ['start_date'], 'verbose_name': 'Work Experience'},
        ),
    ]
