# Generated by Django 3.1.3 on 2021-01-26 11:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('landing_page', '0010_auto_20210126_1207'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='education',
            options={'ordering': ['start_date'], 'verbose_name': 'Education', 'verbose_name_plural': 'Education'},
        ),
        migrations.AlterModelOptions(
            name='siteconfiguration',
            options={'verbose_name': 'Site Configuration', 'verbose_name_plural': 'Site Configuration'},
        ),
        migrations.AlterModelOptions(
            name='work',
            options={'ordering': ['start_date'], 'verbose_name': 'Work Experience', 'verbose_name_plural': 'Work Experience'},
        ),
    ]
